const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktop", {
  enabled: true,
  startDrag(id) { ipcRenderer.send("start-drag", id); },
  revealFile(id) { ipcRenderer.send("reveal-file", id); },
  copyFilePath(id) { return ipcRenderer.invoke("copy-file-path", id); },
  listLibrary(options) { return ipcRenderer.invoke("library-list", options); },
  libraryCount(filters) { return ipcRenderer.invoke("library-count", filters); },
  searchLibrary(query, options) { return ipcRenderer.invoke("library-search", query, options); },
  smartFolder(name, limit) { return ipcRenderer.invoke("library-smart", name, limit); },
  findDuplicates() { return ipcRenderer.invoke("library-duplicates"); },
  findSimilar(id) { return ipcRenderer.invoke("library-similar", id); },
  markAssetUsed(id) { return ipcRenderer.invoke("library-mark-used", id); },
  renderSoundLab(id, settings) { return ipcRenderer.invoke("sound-lab-render", id, settings); },
  updateAsset(id, changes) { return ipcRenderer.invoke("library-update", id, changes); },
  removeAsset(id) { return ipcRenderer.invoke("library-remove", id); },
  importFiles() { return ipcRenderer.invoke("import-files"); },
  importFolder() { return ipcRenderer.invoke("import-folder"); },
  searchGoogleImages(query, mode) { return ipcRenderer.invoke("google-image-search", query, mode); },
  searchMyInstants(query) { return ipcRenderer.invoke("myinstants-search", query); },
  cacheMyInstant(item) { return ipcRenderer.invoke("myinstants-cache", item); },
  resolveGoogleImage(query, mode, index, fallback) { return ipcRenderer.invoke("google-image-resolve", query, mode, index, fallback); },
  cacheRemoteImage(url, title) { return ipcRenderer.invoke("cache-remote-image", url, title); },
  copyRemoteImage(url, title) { return ipcRenderer.invoke("copy-remote-image", url, title); },
  copyText(value) { return ipcRenderer.invoke("copy-text", value); },
  cacheStatus() { return ipcRenderer.invoke("cache-status"); },
  clearCache(kind) { return ipcRenderer.invoke("cache-clear", kind); },
  setCacheLimit(limit) { return ipcRenderer.invoke("cache-limit", limit); },
  getAppSettings() { return ipcRenderer.invoke("app-settings-get"); },
  updateAppSettings(changes) { return ipcRenderer.invoke("app-settings-update", changes); },
  resetAppSettings() { return ipcRenderer.invoke("app-settings-reset"); },
  chooseFolder(key) { return ipcRenderer.invoke("choose-folder", key); },
  listNativeSfx() { return ipcRenderer.invoke("native-sfx-list"); },
  clearNativeSfxCache() { return ipcRenderer.invoke("native-sfx-clear-cache"); },
  listBoards() { return ipcRenderer.invoke("boards-list"); },
  loadBoard(id) { return ipcRenderer.invoke("board-load", id); },
  saveBoard(board) { return ipcRenderer.invoke("board-save", board); },
  deleteBoard(id) { return ipcRenderer.invoke("board-delete", id); },
  importBoardImages() { return ipcRenderer.invoke("board-import-images"); },
  importBoardUrl(url) { return ipcRenderer.invoke("board-import-url", url); },
  exportBoard(dataUrl, name, format) { return ipcRenderer.invoke("board-export", dataUrl, name, format); },
  toggleFullscreen() { return ipcRenderer.invoke("window-fullscreen"); },
  setAlwaysOnTop(enabled) { return ipcRenderer.invoke("window-always-on-top", enabled); },
  setThemeAccent(color) { return ipcRenderer.invoke("theme-accent", color); },
  getAppInfo() { return ipcRenderer.invoke("app-info"); },
  universalSearch(query) { return ipcRenderer.invoke("universal-search", query); },
  listTray() { return ipcRenderer.invoke("tray-list"); },
  addTray(id) { return ipcRenderer.invoke("tray-add", id); },
  removeTray(id) { return ipcRenderer.invoke("tray-remove", id); },
  clearTray() { return ipcRenderer.invoke("tray-clear"); },
  listProjects(includeArchived) { return ipcRenderer.invoke("projects-list", includeArchived); },
  saveProject(project) { return ipcRenderer.invoke("project-save", project); },
  deleteProject(id) { return ipcRenderer.invoke("project-delete", id); },
  addProjectAsset(projectId, assetId) { return ipcRenderer.invoke("project-add-asset", projectId, assetId); },
  workspaceRules(rules) { return ipcRenderer.invoke("workspace-rules", rules); },
  listWatchedFolders() { return ipcRenderer.invoke("watched-folders"); },
  addWatchedFolder() { return ipcRenderer.invoke("watched-folder-add"); },
  removeWatchedFolder(folder) { return ipcRenderer.invoke("watched-folder-remove", folder); },
  addBrowserHistory(item) { return ipcRenderer.invoke("browser-history-add", item); },
  envatoStatus() { return ipcRenderer.invoke("envato-status"); },
  setEnvatoToken(token) { return ipcRenderer.invoke("envato-set-token", token); },
  testEnvato() { return ipcRenderer.invoke("envato-test"); },
  searchEnvato(query) { return ipcRenderer.invoke("envato-search", query); },
  assistantStatus() { return ipcRenderer.invoke("assistant-status"); },
  saveAssistantKey(key) { return ipcRenderer.invoke("assistant-save-key", key); },
  assistantChat(messages, project) { return ipcRenderer.invoke("assistant-chat", messages, project); },
  showMainResult(item) { return ipcRenderer.invoke("show-main-result", item); },
  showMiniImagePreview(item) { ipcRenderer.send("mini-preview-show", item); },
  hideMiniImagePreview() { ipcRenderer.send("mini-preview-hide"); },
  hideMini() { ipcRenderer.send("mini-hide"); },
  onDragState(callback) { ipcRenderer.on("drag-state", (_event, state) => callback(state)); },
  onBrowserDownload(callback) { ipcRenderer.on("browser-download", (_event, result) => callback(result)); },
  onIndexProgress(callback) { ipcRenderer.on("index-progress", (_event, result) => callback(result)); },
  onLibraryUpdated(callback) { ipcRenderer.on("library-updated", (_event, result) => callback(result)); },
  onUniversalResult(callback) { ipcRenderer.on("universal-result", (_event, result) => callback(result)); },
  onMiniFocus(callback) { ipcRenderer.on("mini-focus", callback); },
  onMiniPreview(callback) { ipcRenderer.on("mini-preview-data", (_event, item) => callback(item)); },
});
